[features]
seeds = false
skip-lint = false
[programs.localnet]
unidouble = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/mcesbron/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
